ifeq ($(strip ${CFG_BOARDNAME}),"BCM96338")
BSPOBJS +=               \
	 bcm6338_rom_boot.o
endif
ifeq ($(strip ${CFG_BOARDNAME}),"BCM96348")
BSPOBJS +=               \
	 bcm6348_rom_boot.o
endif
ifeq ($(strip ${CFG_BOARDNAME}),"BCM96358")
BSPOBJS +=               \
	 bcm6358_rom_boot.o \
	 sdramDqs.o
endif

BSPOBJS +=           \
	 bcm63xx_main.o


